/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.awt.BorderLayout;
/**
 *
 * @author user
 */
public class dashboard_admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public dashboard_admin() {
        initComponents();
    }
    
    private void showPanel(javax.swing.JPanel panel) {
        A_panel_utama.removeAll();                         // hapus isi panel utama
        A_panel_utama.setLayout(new java.awt.BorderLayout());
        A_panel_utama.add(panel, java.awt.BorderLayout.CENTER);
        A_panel_utama.revalidate();                        // refresh tampilan
        A_panel_utama.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A_txt_1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        A_txt_2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        A_btn_beranda = new javax.swing.JButton();
        A_btn_daftar_user = new javax.swing.JButton();
        A_btn_lap_keuangan = new javax.swing.JButton();
        A_btn_lap_transaksi = new javax.swing.JButton();
        A_btn_lap_pembelian = new javax.swing.JButton();
        A_btn_daftar_brg = new javax.swing.JButton();
        A_btn_kategori = new javax.swing.JButton();
        A_btn_pembelian = new javax.swing.JButton();
        A_panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1870, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_txt_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        A_txt_1.setForeground(new java.awt.Color(255, 255, 255));
        A_txt_1.setText("ADMINE SAKPORE");
        jPanel1.add(A_txt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 720, 100));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton1.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 40, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Posisi : ADMIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 60, 220, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("=");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("=");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 80));

        A_txt_2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        A_txt_2.setForeground(new java.awt.Color(255, 255, 255));
        A_txt_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_txt_2.setText("ALMADANI");
        jPanel1.add(A_txt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 30, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 120));

        jPanel2.setBackground(java.awt.Color.gray);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_btn_beranda.setBackground(java.awt.Color.darkGray);
        A_btn_beranda.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        A_btn_beranda.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_beranda.setText("BERANDA");
        A_btn_beranda.setOpaque(true);
        A_btn_beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_berandaActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 60));

        A_btn_daftar_user.setBackground(java.awt.Color.darkGray);
        A_btn_daftar_user.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        A_btn_daftar_user.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_daftar_user.setText("DAFTAR USER");
        A_btn_daftar_user.setOpaque(true);
        A_btn_daftar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_daftar_userActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_daftar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 230, 60));

        A_btn_lap_keuangan.setBackground(java.awt.Color.darkGray);
        A_btn_lap_keuangan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_lap_keuangan.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_lap_keuangan.setText("LAPORAN KEUANGAN");
        A_btn_lap_keuangan.setOpaque(true);
        A_btn_lap_keuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_lap_keuanganActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_lap_keuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 60));

        A_btn_lap_transaksi.setBackground(java.awt.Color.darkGray);
        A_btn_lap_transaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_lap_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_lap_transaksi.setText("LAPORAN TRANSAKSI");
        A_btn_lap_transaksi.setOpaque(true);
        A_btn_lap_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_lap_transaksiActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_lap_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, 60));

        A_btn_lap_pembelian.setBackground(java.awt.Color.darkGray);
        A_btn_lap_pembelian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_lap_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_lap_pembelian.setText("LAPORAN PEMBELIAN");
        A_btn_lap_pembelian.setOpaque(true);
        A_btn_lap_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_lap_pembelianActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_lap_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 230, 60));

        A_btn_daftar_brg.setBackground(java.awt.Color.darkGray);
        A_btn_daftar_brg.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        A_btn_daftar_brg.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_daftar_brg.setText("DAFTAR BARANG");
        A_btn_daftar_brg.setOpaque(true);
        A_btn_daftar_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_daftar_brgActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_daftar_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 230, 60));

        A_btn_kategori.setBackground(java.awt.Color.darkGray);
        A_btn_kategori.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        A_btn_kategori.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_kategori.setText("KATEGORI BARANG");
        A_btn_kategori.setOpaque(true);
        A_btn_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_kategoriActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 230, 60));

        A_btn_pembelian.setBackground(java.awt.Color.darkGray);
        A_btn_pembelian.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        A_btn_pembelian.setForeground(new java.awt.Color(255, 255, 255));
        A_btn_pembelian.setText("PEMBELIAN BRG");
        A_btn_pembelian.setOpaque(true);
        A_btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_pembelianActionPerformed(evt);
            }
        });
        jPanel2.add(A_btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 230, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 960));

        A_panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        A_panel_utama.setMinimumSize(new java.awt.Dimension(1650, 940));

        javax.swing.GroupLayout A_panel_utamaLayout = new javax.swing.GroupLayout(A_panel_utama);
        A_panel_utama.setLayout(A_panel_utamaLayout);
        A_panel_utamaLayout.setHorizontalGroup(
            A_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1650, Short.MAX_VALUE)
        );
        A_panel_utamaLayout.setVerticalGroup(
            A_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );

        getContentPane().add(A_panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 1650, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_btn_berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_berandaActionPerformed
        // TODO add your handling code here:
        beranda_admin beranda = new beranda_admin();   // buat instance panel
        showPanel(beranda);
    }//GEN-LAST:event_A_btn_berandaActionPerformed

    private void A_btn_daftar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_daftar_userActionPerformed
        // TODO add your handling code here:
        daftar_user user = new daftar_user();   // buat instance panel
        showPanel(user);
    }//GEN-LAST:event_A_btn_daftar_userActionPerformed

    private void A_btn_lap_keuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_lap_keuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btn_lap_keuanganActionPerformed

    private void A_btn_lap_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_lap_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btn_lap_transaksiActionPerformed

    private void A_btn_lap_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_lap_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btn_lap_pembelianActionPerformed

    private void A_btn_daftar_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_daftar_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btn_daftar_brgActionPerformed

    private void A_btn_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_kategoriActionPerformed
        // TODO add your handling code here:
        kategori_barang kategori = new kategori_barang();   // buat instance panel
        showPanel(kategori);
    }//GEN-LAST:event_A_btn_kategoriActionPerformed

    private void A_btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btn_pembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btn_pembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_btn_beranda;
    private javax.swing.JButton A_btn_daftar_brg;
    private javax.swing.JButton A_btn_daftar_user;
    private javax.swing.JButton A_btn_kategori;
    private javax.swing.JButton A_btn_lap_keuangan;
    private javax.swing.JButton A_btn_lap_pembelian;
    private javax.swing.JButton A_btn_lap_transaksi;
    private javax.swing.JButton A_btn_pembelian;
    private javax.swing.JPanel A_panel_utama;
    private javax.swing.JLabel A_txt_1;
    private javax.swing.JLabel A_txt_2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
