/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

/**
 *
<<<<<<< HEAD
 * @author LAB FO-01
=======
 * @author Acer Aspire Lite 15
>>>>>>> ea7988d2a259bb5c89ab50532c6361d8413129d0
 */
public class tambah_barang extends javax.swing.JPanel {

    /**
<<<<<<< HEAD
     * Creates new form tambah_barang
=======
     * Creates new form NewJPanel
>>>>>>> ea7988d2a259bb5c89ab50532c6361d8413129d0
     */
    public tambah_barang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
=======
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1700, 940));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAMBAH DAFTAR BARANG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 680, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NAMA BARANG  :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("KATEGORI            :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 280, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("HARGA BARANG :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 280, 70));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("HARGA JUAL        :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 280, 70));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setMaximumSize(new java.awt.Dimension(71, 22));
        jTextField2.setMinimumSize(new java.awt.Dimension(71, 22));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 400, 70));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setMaximumSize(new java.awt.Dimension(71, 22));
        jTextField3.setMinimumSize(new java.awt.Dimension(71, 22));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 400, 70));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setMaximumSize(new java.awt.Dimension(71, 22));
        jTextField5.setMinimumSize(new java.awt.Dimension(71, 22));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 400, 70));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setMaximumSize(new java.awt.Dimension(71, 22));
        jTextField6.setMinimumSize(new java.awt.Dimension(71, 22));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 400, 70));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 400, 70));

        jButton1.setBackground(java.awt.Color.green);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jButton1.setText("SIMPAN");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 680, 90));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("KODE BARANG    :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 70));
>>>>>>> ea7988d2a259bb5c89ab50532c6361d8413129d0
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
=======
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
>>>>>>> ea7988d2a259bb5c89ab50532c6361d8413129d0
    // End of variables declaration//GEN-END:variables
}
